# -*- coding: utf-8 -*-
"""Pedra_Papel_Tesoura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cm6VqAumxMnEFFbS1C9AbZDzSZGNSru2

**ESTUDO DE CASO:**

Pedra, Papel e Tesoura é um jogo de mão simples e popular, geralmente disputado entre duas pessoas.

O objetivo é derrotar o oponente escolhendo um de três objetos, cada qual com uma vantagem sobre um objeto e uma desvantagem sobre o outro.As regras de vitória são as seguintes:

-Pedra vence a Tesoura (quebrando-a);
-Tesoura vence o Papel (cortando-o) e
-Papel vence a Pedra (cobrindo-a).

Se ambos os jogadores escolherem o mesmo objeto, a rodada resulta em um empate
"""

import getpass

print("----------------------")
print("   Seja bem vindo     ")
print("----------------------")
print("Pedra vence a Tesoura")
print("Tesoura vence o Papel")
print("Papel vence a Pedra\n  ")

placar_p1 = 0
placar_p2 = 0
placar_empate = 0

while True:

  jogadas1 = ['pedra', 'papel', 'tesoura']
  jogadas2 = ['pedra', 'papel', 'tesoura']


  player_1 = getpass.getpass(f'Jogador 1: {jogadas1[0]}, {jogadas1[1]} ou {jogadas1[2]}' ).lower().strip()
  player_2 = getpass.getpass(f'Jogador 2: {jogadas2[0]}, {jogadas2[1]} ou {jogadas2[2]}' ).lower().strip()




  vence = {

          "pedra"  :    "tesoura",
          "tesoura":    "papel",
          "papel"  :    "pedra"


  }


  if player_1 in jogadas1 and player_2 in jogadas2:

    if player_1 == player_2:

      print('Empate')
      placar_empate += 1

    elif vence[player_1] ==player_2:

      print("----------------")
      print('Jogador 1 venceu')
      print("----------------")
      placar_p1 += 1

    else:
      print("----------------")
      print('Jogador 2 venceu')
      print("----------------")
      placar_p2 += 1

    print('Jogador 1:', player_1, '\nJogador 2:', player_2)

  else:
    print('Alguém digitou uma opção que não existe')

  continuar = input("Jogar novamente: 1\nEncerrar: 2\n")

  if continuar ==  '2':

    print("------ JOGO ENCERRADO ------")
    print(f'      Placar final:         \n Jogador 1: {placar_p1} \n Jogador 2: {placar_p2}')



    break